### ISSUE TITLE
One image in perspective merged with other image 

### ISSUE THREAD

**Issue by gustavosapienza** [wanadev/perspective.js#2]
Hi, how are you?

I have a big trouble, I'm using this component and I need to change one image to perspective and apply this to other one, how should i do?

This is the example:
http://jsfiddle.net/gustavosapienza/b3mt48gv/

Thanks a lot!

**Comment by flozz** [comment]
Hello,

You can use 2 canvas or play with the [global composite operations](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation) like this:

* http://jsfiddle.net/b3mt48gv/6/

Regards,

**Comment by gustavosapienza** [comment]
Woooowwww

Great! You saved my life!

Thanks a lot!
