### ISSUE TITLE
Created a component with perspective.js, but have problem onload

### ISSUE THREAD

**Issue by gustavosapienza** [wanadev/perspective.js#3]
Hi, how are you?

At the last time you help-me and saved my life, I need one more favor,

I created this script whiot this component:
http://jsfiddle.net/gustavosapienza/7jv207ec/

But onload have a error, i need to load the page some times to run correctly the scripts, do you know whats happen? Only on Firefox is working

Thanks a lot!

**Comment by flozz** [comment]
Hello,

You have to wait for the images to be loaded before trying to transform / draw them:

```javascript
var img = new Image();
img.onload = function (event) {
    // Code that use the image here...
};
img.src = "http://example.com/image.png";
```

http://jsfiddle.net/7jv207ec/1/

-------

Please do not open issues for questions that are not related to the project itself. If you need help with Javascript, you can ask your questions on sites like [StackOverflow](https://stackoverflow.com/).

**Comment by gustavosapienza** [comment]
Thanks flozz! You really helped me!
Thanks a lot!
