### ISSUE TITLE
Problem on turn image 90 degrees

### ISSUE THREAD

**Issue by gustavosapienza** [wanadev/perspective.js#4]
Hi, somebody could help me?

I am using perspective.js on my project, but when I turn the image on 90 degrees or more, it hide!

The link of my project:
http://www.petmaker.com.br/admin/EcommerceNew/Menus/matrizes.asp?idproduto=64&imagem=g40272_CARTEIRA_frente-em-pe.png&campo=MatrixDesenho2

I am using like this:
http://www.html5.jp/test/perspective_canvas/demo1_en.html

Thanks a lot!

**Comment by flozz** [comment]
Hello,

this is a limitation of the lib, there is no solution...

Regards,
