### ISSUE TITLE
Request to be able to pick source corners

### ISSUE THREAD

**Issue by csaftoiu** [wanadev/perspective.js#6]
With this lib you can warp an image to any 4 corners, but I have a need to warp 4 source pts from the image to 4 destination points

**Comment by flozz** [comment]
This should be doable with a bit of math, I did it once, but this is not in the scope of this library.
![capture d ecran de 2017-11-08 09-43-50](https://user-images.githubusercontent.com/971438/32539395-8da2fd6a-c469-11e7-9bc8-ea6214ca9005.png)
